INSERT INTO public.contract_templates (nome, tipo, descricao, conteudo, campos) VALUES
(
  'Contrato de Prestação de Serviços',
  'prestacao_servicos',
  'Contrato padrão para prestação de serviços de tecnologia e automação',
  E'CONTRATO DE PRESTAÇÃO DE SERVIÇOS\n\nPelo presente instrumento particular, as partes:\n\nCONTRATANTE: {{nome_contratante}}, inscrito(a) no CNPJ/CPF sob o nº {{documento_contratante}}, com sede/domicílio em {{endereco_contratante}}, neste ato representado(a) por {{representante_contratante}}.\n\nCONTRATADA: {{nome_contratada}}, inscrita no CNPJ sob o nº {{documento_contratada}}, com sede em {{endereco_contratada}}, neste ato representada por {{representante_contratada}}.\n\nCLÁUSULA PRIMEIRA - DO OBJETO\nO presente contrato tem por objeto a prestação dos seguintes serviços: {{descricao_servicos}}.\n\nCLÁUSULA SEGUNDA - DO PRAZO\nO presente contrato terá vigência de {{prazo_meses}} meses, com início em {{data_inicio}} e término em {{data_termino}}, podendo ser renovado mediante acordo entre as partes.\n\nCLÁUSULA TERCEIRA - DO VALOR E PAGAMENTO\nPelo serviço prestado, a CONTRATANTE pagará à CONTRATADA o valor de R$ {{valor_total}} ({{valor_extenso}}), a ser pago {{forma_pagamento}}.\n\nCLÁUSULA QUARTA - DAS OBRIGAÇÕES DA CONTRATADA\na) Executar os serviços com qualidade e dentro dos prazos acordados;\nb) Manter sigilo sobre todas as informações obtidas;\nc) Fornecer relatórios periódicos sobre o andamento dos serviços.\n\nCLÁUSULA QUINTA - DAS OBRIGAÇÕES DA CONTRATANTE\na) Fornecer informações e acessos necessários;\nb) Efetuar os pagamentos nas datas acordadas;\nc) Designar um responsável para acompanhar a execução.\n\nCLÁUSULA SEXTA - DA RESCISÃO\nRescisão mediante notificação com antecedência mínima de {{prazo_rescisao}} dias.\n\nCLÁUSULA SÉTIMA - DA CONFIDENCIALIDADE\nSigilo sobre informações confidenciais por prazo indeterminado.\n\nCLÁUSULA OITAVA - DO FORO\nForo da comarca de {{cidade_foro}}/{{estado_foro}}.\n\n{{cidade_assinatura}}, {{data_assinatura}}.\n\n\n___________________________________\n{{nome_contratante}}\nCONTRATANTE\n\n\n___________________________________\n{{nome_contratada}}\nCONTRATADA',
  '[{"key":"nome_contratante","label":"Nome do Contratante","type":"text","required":true},{"key":"documento_contratante","label":"CNPJ/CPF do Contratante","type":"text","required":true},{"key":"endereco_contratante","label":"Endereço do Contratante","type":"text","required":true},{"key":"representante_contratante","label":"Representante do Contratante","type":"text","required":true},{"key":"nome_contratada","label":"Nome da Contratada","type":"text","required":true},{"key":"documento_contratada","label":"CNPJ da Contratada","type":"text","required":true},{"key":"endereco_contratada","label":"Endereço da Contratada","type":"text","required":true},{"key":"representante_contratada","label":"Representante da Contratada","type":"text","required":true},{"key":"descricao_servicos","label":"Descrição dos Serviços","type":"textarea","required":true},{"key":"prazo_meses","label":"Prazo (meses)","type":"text","required":true},{"key":"data_inicio","label":"Data de Início","type":"date","required":true},{"key":"data_termino","label":"Data de Término","type":"date","required":true},{"key":"valor_total","label":"Valor Total (R$)","type":"text","required":true},{"key":"valor_extenso","label":"Valor por Extenso","type":"text","required":true},{"key":"forma_pagamento","label":"Forma de Pagamento","type":"text","required":true},{"key":"prazo_rescisao","label":"Prazo para Rescisão (dias)","type":"text","required":true,"default":"30"},{"key":"cidade_foro","label":"Cidade do Foro","type":"text","required":true},{"key":"estado_foro","label":"Estado do Foro","type":"text","required":true},{"key":"cidade_assinatura","label":"Cidade da Assinatura","type":"text","required":true},{"key":"data_assinatura","label":"Data da Assinatura","type":"date","required":true}]'::jsonb
),
(
  'Contrato SaaS / Licenciamento',
  'saas',
  'Contrato de uso de software como serviço (SaaS) e licenciamento',
  E'CONTRATO DE LICENCIAMENTO DE SOFTWARE COMO SERVIÇO (SaaS)\n\nLICENCIADOR: {{nome_licenciador}}, CNPJ {{documento_licenciador}}, sede em {{endereco_licenciador}}.\n\nLICENCIADO: {{nome_licenciado}}, CNPJ/CPF {{documento_licenciado}}, sede em {{endereco_licenciado}}.\n\nCLÁUSULA PRIMEIRA - DO OBJETO\nLicença de uso do software \"{{nome_software}}\", modalidade SaaS, incluindo: {{funcionalidades}}.\n\nCLÁUSULA SEGUNDA - DO PLANO\nPlano \"{{nome_plano}}\": até {{limite_usuarios}} usuários, {{limite_armazenamento}} armazenamento, suporte via {{canais_suporte}}.\n\nCLÁUSULA TERCEIRA - DO PRAZO\nVigência de {{prazo_meses}} meses a partir de {{data_inicio}}, renovável automaticamente salvo aviso com {{prazo_cancelamento}} dias.\n\nCLÁUSULA QUARTA - DO VALOR\nR$ {{valor_mensal}} ({{valor_extenso}}) mensais, vencimento dia {{dia_vencimento}}.\n\nCLÁUSULA QUINTA - SLA\nDisponibilidade mínima de {{sla_disponibilidade}}%.\n\nCLÁUSULA SEXTA - PROPRIEDADE INTELECTUAL\nSoftware é propriedade exclusiva do LICENCIADOR.\n\nCLÁUSULA SÉTIMA - LGPD\nCumprimento da Lei nº 13.709/2018.\n\nCLÁUSULA OITAVA - RESCISÃO\nAviso prévio de {{prazo_cancelamento}} dias.\n\nCLÁUSULA NONA - FORO\nComarca de {{cidade_foro}}/{{estado_foro}}.\n\n{{cidade_assinatura}}, {{data_assinatura}}.\n\n\n___________________________________\n{{nome_licenciador}}\nLICENCIADOR\n\n\n___________________________________\n{{nome_licenciado}}\nLICENCIADO',
  '[{"key":"nome_licenciador","label":"Nome do Licenciador","type":"text","required":true},{"key":"documento_licenciador","label":"CNPJ do Licenciador","type":"text","required":true},{"key":"endereco_licenciador","label":"Endereço do Licenciador","type":"text","required":true},{"key":"nome_licenciado","label":"Nome do Licenciado","type":"text","required":true},{"key":"documento_licenciado","label":"CNPJ/CPF do Licenciado","type":"text","required":true},{"key":"endereco_licenciado","label":"Endereço do Licenciado","type":"text","required":true},{"key":"nome_software","label":"Nome do Software","type":"text","required":true},{"key":"funcionalidades","label":"Funcionalidades","type":"textarea","required":true},{"key":"nome_plano","label":"Nome do Plano","type":"text","required":true},{"key":"limite_usuarios","label":"Limite de Usuários","type":"text","required":true},{"key":"limite_armazenamento","label":"Armazenamento","type":"text","required":true},{"key":"canais_suporte","label":"Canais de Suporte","type":"text","required":true,"default":"e-mail e WhatsApp"},{"key":"prazo_meses","label":"Prazo (meses)","type":"text","required":true,"default":"12"},{"key":"data_inicio","label":"Data de Início","type":"date","required":true},{"key":"prazo_cancelamento","label":"Prazo Cancelamento (dias)","type":"text","required":true,"default":"30"},{"key":"valor_mensal","label":"Valor Mensal (R$)","type":"text","required":true},{"key":"valor_extenso","label":"Valor por Extenso","type":"text","required":true},{"key":"dia_vencimento","label":"Dia Vencimento","type":"text","required":true,"default":"10"},{"key":"sla_disponibilidade","label":"SLA (%)","type":"text","required":true,"default":"99.5"},{"key":"cidade_foro","label":"Cidade do Foro","type":"text","required":true},{"key":"estado_foro","label":"Estado do Foro","type":"text","required":true},{"key":"cidade_assinatura","label":"Cidade da Assinatura","type":"text","required":true},{"key":"data_assinatura","label":"Data da Assinatura","type":"date","required":true}]'::jsonb
),
(
  'Acordo de Confidencialidade (NDA)',
  'nda',
  'Acordo de não divulgação de informações confidenciais',
  E'ACORDO DE CONFIDENCIALIDADE E NÃO DIVULGAÇÃO (NDA)\n\nPARTE REVELADORA: {{nome_reveladora}}, CNPJ {{documento_reveladora}}, sede em {{endereco_reveladora}}.\n\nPARTE RECEPTORA: {{nome_receptora}}, CNPJ/CPF {{documento_receptora}}, sede em {{endereco_receptora}}.\n\nCLÁUSULA PRIMEIRA - OBJETO\nConfidencialidade no contexto de: {{contexto_projeto}}.\n\nCLÁUSULA SEGUNDA - INFORMAÇÕES CONFIDENCIAIS\nTodos os dados, documentos, especificações, know-how, segredos comerciais, estratégias, código-fonte e listas de clientes.\n\nCLÁUSULA TERCEIRA - OBRIGAÇÕES\na) Manter estrito sigilo;\nb) Não divulgar ou utilizar para fins diversos;\nc) Limitar acesso aos colaboradores necessários;\nd) Devolver ou destruir ao término.\n\nCLÁUSULA QUARTA - EXCEÇÕES\nInformações públicas, já conhecidas, de terceiros sem restrição, ou exigidas judicialmente.\n\nCLÁUSULA QUINTA - PRAZO\nVigência de {{prazo_anos}} anos, obrigações mantidas por {{prazo_pos_termino}} anos após o término.\n\nCLÁUSULA SEXTA - PENALIDADES\nMulta de R$ {{valor_multa}} ({{multa_extenso}}).\n\nCLÁUSULA SÉTIMA - FORO\nComarca de {{cidade_foro}}/{{estado_foro}}.\n\n{{cidade_assinatura}}, {{data_assinatura}}.\n\n\n___________________________________\n{{nome_reveladora}}\nPARTE REVELADORA\n\n\n___________________________________\n{{nome_receptora}}\nPARTE RECEPTORA\n\nTESTEMUNHAS:\n1. {{testemunha1_nome}} - CPF: {{testemunha1_cpf}}\n2. {{testemunha2_nome}} - CPF: {{testemunha2_cpf}}',
  '[{"key":"nome_reveladora","label":"Parte Reveladora","type":"text","required":true},{"key":"documento_reveladora","label":"CNPJ Reveladora","type":"text","required":true},{"key":"endereco_reveladora","label":"Endereço Reveladora","type":"text","required":true},{"key":"nome_receptora","label":"Parte Receptora","type":"text","required":true},{"key":"documento_receptora","label":"CNPJ/CPF Receptora","type":"text","required":true},{"key":"endereco_receptora","label":"Endereço Receptora","type":"text","required":true},{"key":"contexto_projeto","label":"Contexto/Projeto","type":"textarea","required":true},{"key":"prazo_anos","label":"Prazo (anos)","type":"text","required":true,"default":"2"},{"key":"prazo_pos_termino","label":"Pós-Término (anos)","type":"text","required":true,"default":"5"},{"key":"valor_multa","label":"Valor da Multa (R$)","type":"text","required":true},{"key":"multa_extenso","label":"Multa por Extenso","type":"text","required":true},{"key":"cidade_foro","label":"Cidade do Foro","type":"text","required":true},{"key":"estado_foro","label":"Estado do Foro","type":"text","required":true},{"key":"cidade_assinatura","label":"Cidade da Assinatura","type":"text","required":true},{"key":"data_assinatura","label":"Data da Assinatura","type":"date","required":true},{"key":"testemunha1_nome","label":"Testemunha 1","type":"text","required":true},{"key":"testemunha1_cpf","label":"CPF Testemunha 1","type":"text","required":true},{"key":"testemunha2_nome","label":"Testemunha 2","type":"text","required":true},{"key":"testemunha2_cpf","label":"CPF Testemunha 2","type":"text","required":true}]'::jsonb
);