// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyhkefwbqntdhocxjxes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5aGtlZndicW50ZGhvY3hqeGVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2NDM3MTQsImV4cCI6MjA3ODIxOTcxNH0.1q50Ha4ByzpbHCEM3590The1DZSVpoaQMyRq75h65XE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});